name: Build & Deploy Aurora blog

on: 
  push: 
    branches: 
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    # or just '3.13 'python3 3.13''
    # Install dependencies and build site
    - run: |
        pip install aurora-ssg
        aurora build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
        source_dir: '_site'

    - name: Sync files to S3
      run: |
        aws s3 sync ./_site s3://${{ secrets.AWS_S3_BUCKET }} --delete
   
  #    env:
  #      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  #      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #      AWS_REGION: 'us-east-1'
  #      SOURCE_DIR: '_site'